### ISSUE TITLE
log spam

### ISSUE THREAD

**Issue by ryleu** [Globox1997/Stamina#1]
### Minecraft Version

1.21.x

### Mod Loader Version

N/A

### Mod Version

1.0.0

### Describe the Issue

![image](https://github.com/user-attachments/assets/893229c0-1cad-4eab-8b34-5a2261d42d8f)

### latest.log

https://mclo.gs/171vjTP

### Do you use any other mods except the required ones?

Yep, but your mod is the one spamming the logs.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/Stamina/commit/39481ce59ffd3294cf5d148b1a350d4303fd4875](https://github.com/Globox1997/Stamina/commit/39481ce59ffd3294cf5d148b1a350d4303fd4875)
